export enum Constants {
    LOGGER = 'LOGGER',
    CONFIG_SERVICE = 'CONFIG_SERVICE',
    HOME_CONTROLLER = 'HOME_CONTROLLER',
    TODO_CONTROLLER = 'TODO_CONTROLLER',
    TODO_SERVICE = 'TODO_SERVICE',
    TODO_REPOSITORY = 'TODO_REPOSITORY',
}
